spring:
  config:
    activate:
      on-profile: "qa"
build:
  version: "2.0"
  
loans:
  message: "Welcome to EazyBank cards related QA APIs "
  contactDetails:
    name: "Sandy - Developer"
    email: "sandy@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345

